// <auto-generated />
namespace ChatApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ThreeNewProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThreeNewProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201407202215013_ThreeNewProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
